 [build]
  publish = "storybook-static"
  command = "npm run lint && npm test && npm run build && npm run build-storybook"

[build.environment]
  NODE_VERSION = "24.0.0"
  DOTENV_DISPLAY_WARNING = "none"
  STORYBOOK_EXAMPLE_APP ="true"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
