// Author https://github.com/schloerke/cranvasOLD/blob/master/files/data/chocolates.csv

export default [
  {
    name: 'Noir 86% Cacao',
    manufacturer: 'Cote DO\'r',
    country: 'Belgium',
    type: 'Dark',
    calories: 460,
    protein: 8.3,
    isOutOfStock: false,
  },
  {
    name: 'Solid Dark Chocolate Bar',
    manufacturer: 'Godiva',
    country: 'Belgium',
    type: 'Dark',
    calories: 534,
    protein: 6.9,
    isOutOfStock: true,
  },
  {
    name: 'Dark Chocolate - 70% Cacao',
    manufacturer: 'Nacional De Chocolates',
    country: 'Colombia',
    type: 'Dark',
    calories: 571,
    protein: 7.1,
    isOutOfStock: false,
  },
  {
    name: 'Dark Chocolate - 65% Cacao',
    manufacturer: 'Nacional De Chocolates',
    country: 'Colombia',
    type: 'Dark',
    calories: 585,
    protein: 5.7,
    isOutOfStock: false,
  },
  {
    name: 'Dark Chocolate',
    manufacturer: 'Merci',
    country: 'France',
    type: 'Dark',
    calories: 578,
    protein: 7.8,
    isOutOfStock: false,
  },
  {
    name: 'Noir 76% Cocoa',
    manufacturer: 'Poulain',
    country: 'France',
    type: 'Dark',
    calories: 600,
    protein: 8.7,
    isOutOfStock: true,
  },
  {
    name: 'Ultime Noir 86% Cocoa',
    manufacturer: 'Poulain',
    country: 'France',
    type: 'Dark',
    calories: 640,
    protein: 10.3,
    isOutOfStock: false,
  },
  {
    name: 'Dark Chocolate Bar 86%',
    manufacturer: 'Poulain',
    country: 'Switzerland',
    type: 'Dark',
    calories: 640,
    protein: 10.1,
    isOutOfStock: false,
  },
  {
    name: 'Dark w/ Honey and Almond Nougat',
    manufacturer: 'Toblerone',
    country: 'Switzerland',
    type: 'Dark',
    calories: 484,
    protein: 6.4,
    isOutOfStock: false,
  },
  {
    name: 'Dark Chocolate',
    manufacturer: 'Bendicks',
    country: 'UK',
    type: 'Dark',
    calories: 560,
    protein: 9.6,
    isOutOfStock: false,
  },
  {
    name: 'Royal Dark',
    manufacturer: 'Cadbury',
    country: 'UK',
    type: 'Dark',
    calories: 550,
    protein: 5.3,
    isOutOfStock: true,
  },
  {
    name: 'Milk Chocolate',
    manufacturer: 'Ritter Sport',
    country: 'German',
    type: 'Milk',
    calories: 531,
    protein: 7.1,
    isOutOfStock: false,
  },
  {
    name: 'Alpine Milk Chocolate',
    manufacturer: 'Ritter Sport',
    country: 'German',
    type: 'Milk',
    calories: 538,
    protein: 8.3,
    isOutOfStock: false,
  },
  {
    name: 'Milk Chocolate',
    manufacturer: 'Choceur',
    country: 'Switzerland',
    type: 'Milk',
    calories: 575,
    protein: 9.2,
    isOutOfStock: false,
  },
  {
    name: 'Swiss, Milk Gold',
    manufacturer: 'Lindt',
    country: 'Switzerland',
    type: 'Milk',
    calories: 543,
    protein: 7.6,
    isOutOfStock: true,
  },
  {
    name: 'Crunch',
    manufacturer: 'Nestle',
    country: 'Switzerland',
    type: 'Milk',
    calories: 501,
    protein: 4.5,
    isOutOfStock: false,
  },
];
